services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5300:5300"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5300
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=AESCOServices;Username=postgres;Password=nollo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=AESCOServices
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nollo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge